---
- hosts: localhost
  tasks:
    - name: Cria pasta de logs
      file:
        path: /tmp/devops-lab
        state: directory
    - name: Registra treino
      copy:
        content: "Treino DevOps em {{ ansible_date_time.iso8601 }}\n"
        dest: /tmp/devops-lab/treino.txt
